root = '.'
tmp_dir = 'dist'

[build]
cmd = 'go build -o dist/xbvr -tags="json1" main.go'
full_bin = 'DEBUG=1 ./dist/xbvr'
include_ext = ['go']
exclude_dir = ['node_modules', 'cache', 'dist', 'ui', 'tmp']
